version: 2.1
 
orbs:
  ruby: circleci/ruby@1.2
 
jobs:
  test:
    parameters:
      ruby-image:
        type: string
    docker:
      - image: << parameters.ruby-image >>
    steps:
      - checkout
      - run:
          name: Install bundler gem
          command: gem install bundler --version '~> 2.2'
      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install
      - ruby/rubocop-check
      - ruby/rspec-test
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-image: ["cimg/ruby:2.6", "cimg/ruby:2.7", "cimg/ruby:3.0", "ruby:3.1.0-preview1"]
